### ISSUE TITLE
Bug or Feature? amqp: SendToChannel without Listener => Error 404 - no exchange

### ISSUE THREAD

**Issue by me23** [moleculerjs/moleculer-channels#37] opened 2022-05-10 08:18 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x ] I am runno exchangening the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository

## Current Behavior

Starting with an fresh instance of rabbitmq and trigger sendToChannel from moleculer i got follow Error:
`
[2022-05-10T07:30:40.939Z] ERROR my-client/CHANNELS: AMQP channel error Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'something.done' in vhost '/'"
`

and the client exits with unhandled Promise-rejection.

As soon if i start a listener for this channel (somthing.done) once, even if i stop the listener again, then it works like expected.

## Expected Behavior

I don't know if its an bug or a feature, but i expected the channel to be created either if the first listener register or if the
first producer send some messages in.

My idea was to send some events with a ttl-value, so if nobody cares about it, it will be deleted.
As soon as one consumer came up, he can use the stored events.
no exchange
## Failure Information

```
[2022-05-10T07:30:40.939Z] ERROR my-client/CHANNELS: AMQP channel error Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'something.done' in vhost '/'"
at Channel.C.accept (/home/me/public_html/moleculer-channel-test/node_modules/amqplib/lib/channel.js:422:17)
    at Connection.mainAccept [as accept] (/home/me/public_html/moleculer-channel-test/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/home/me/public_html/moleculer-channel-test/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at emitReadable_ (node:internal/streams/readable:601:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 404,
  classId: 60,
  methodId: 40
}
[2022-05-10T07:30:40.941Z] ERROR my-client/CHANNELS: AMQP channel closed.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. start a fresh instance of rabbitmq
2. start producer that trigger sendToChannel("event.occured")
3.  => Error

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.21
* NodeJS version: 17.9.0
* Operating System: Ubuntu 22.04
* "@moleculer/channels": "0.1.2",
* "amqplib": "^0.8.0"

### Failure Logs
```

```

**Comment by me23** [comment] 2022-06-01 13:27
Maybe we could define a auto-create option and if it set, the service will check and create the necessary channels on startup?

**Comment by ujwal-setlur** [comment] 2023-03-09 08:26
Just to add, not sure if this is a different issue, but I did the following:

1. from service A, send a message on a channel/topic where there were subscribers. Message was received. 
2. from service A again, sent a message on a channel/topic there were no subscribers. As expected, got an error that there were no subscribers
3. from service A again, send message from step 1 where there are subscribers. It fails!

```
 IllegalOperationError: Channel closed
```

Step 3 should work, since listener is still available!

**Comment by ujwal-setlur** [comment] 2023-03-09 08:43
Just tested with master branch. It is now fixed. Guess I have to ask when it will be released? :-)

**Comment by ujwal-setlur** [comment] 2023-03-09 09:56
I did one more test on the master branch where this code has been merged:

1. Started publisher, but not subscriber. Sent message. No error from publisher side. But message clearly not delivered since there is no subscriber.
2. Started subscriber. No message was received. Is this this expected behavior? I would have thought the message would be received as soon as subscriber comes up.
3. Any new message from publisher after subscriber comes up is delivered.

**Comment by ujwal-setlur** [comment] 2023-03-14 07:52
It did not, or at least I don't think so, and subsequent messages to queues that did exist would also not work. However, this seems have been fixed in the master branch. But now if the queue does not exist, it won't crash, but it does not seem to throw an error either. Message is just swallowed/dropped. I am testing from the REPL console.

**Comment by AndreMaz** [comment] 2023-03-26 20:10
Can you please provide a repro example? I would like to debug the issue

**Comment by me23** [comment] 2023-03-27 07:22
Clone this repo: [https://github.com/me23/moleculer-channels-amqp-test](https://github.com/me23/moleculer-channels-amqp-test)

Failure
1. Start rabbitmq with docker-compose up
2.  start client: node source/client.js
=> Error.

Success:
1. Start rabbitmq with docker-compose up
2. start service: node source/service.js
3.  start client: node source/client.js
 => No Error

**Comment by icebob** [comment] 2023-08-06 12:23
You should define the `publishAssertExchange` to use this feature. More info: https://github.com/moleculerjs/moleculer-channels/pull/63#pullrequestreview-1302006083

**Closed by icebob** 2023-08-06 12:23 UTC
Labels: Need investigate
